### ISSUE TITLE
Bot only works for collecting daily rewards

### ISSUE THREAD

**Issue by DenSwitch** [scmanjarrez/Genshin-Impact-Stats-Telegram-Bot#1]
hi. i can't use bot since it doesn't reply to any of my messages in telegram, but it collects daily rewards as it should. what should i do? ask for info, i'll provide it
![image](https://user-images.githubusercontent.com/47791189/197610023-0a052ee3-87ab-4c63-aaae-5ea376f3f1fc.png)
![image](https://user-images.githubusercontent.com/47791189/197610082-9ffe3cef-2ba1-475c-923b-53044b29b883.png)

**Comment by scmanjarrez** [comment]
Did you create a .config.json file with your information? Have you opened the ports on your vps? Seems like telegram server can't contact with your telegram bot

**Comment by DenSwitch** [comment]
i did. i have opened ports on vps panel, but it's not working anyways. ufw is disabled

**Comment by scmanjarrez** [comment]
Try changing from webhooks to polling, that way we can check if you're getting updates from telegram server; comment from [line 86](https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/blob/master/paimon.py#L89) to [line 97](https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/blob/master/paimon.py#L97) in [paimon.py](https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/blob/master/paimon.py) and uncomment [line 98](https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/blob/f8fa6abd161e0c8a4d098f93605e627aeb28f73d/paimon.py#L98)

**Comment by DenSwitch** [comment]
it seems like it doesn't get any updates
![image](https://user-images.githubusercontent.com/47791189/197617104-7972d8ef-f0ef-445a-93bd-120bd3400643.png)

**Comment by scmanjarrez** [comment]
Change the debug level in 
```python
 logging.basicConfig(
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        level=logging.INFO
    )
```
from INFO to DEBUG and paste the trace (or check that you're receiving OK when the bot is doing HTTP requests)
> Don't forget to remove sensitive information from the trace, like bot tokens or genshin tokens.

**Comment by DenSwitch** [comment]
it gets my commands like it should but i have no reply
![image](https://user-images.githubusercontent.com/47791189/197619697-6320703f-0057-4cc9-bc76-59be62af1eb6.png)

**Comment by scmanjarrez** [comment]
Did you check your telegram uid? If the server connection is working fine, it implies that you're not being marked as "allowed" in the bot. Check https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/blob/ee193c52a826d6d43573852d781c5d2ce9d8c6d0/paimon_cli.py#L42 if your uid is passing the check of allowed clients
```python
    uid = ut.uid(update)
	print(allowed(uid))
```

**Comment by DenSwitch** [comment]
where do i set uid? in .config.json? if so, i've set my id to match telegram id, the same it reports in logs

**Comment by scmanjarrez** [comment]
Yes, .config.json. After adding the line above (print allowed), are your receiving True? Or just remove the `if allowed` line, and keep only the `ut.send` (removing 1 block of identation)

**Comment by DenSwitch** [comment]
i can't add line, bot stops working. trying to do it now...

**Comment by scmanjarrez** [comment]
It should be like this
```python
async def bot_help(update: Update, context: ut.Context) -> None:
    uid = ut.uid(update)
    await ut.send(update, HELP)
```
You should receive at least a response from /start and /help commands

**Comment by DenSwitch** [comment]
yup, it's replying now

**Comment by scmanjarrez** [comment]
Then, your telegram uid isn't correct. 
Use this to set the telegram uid in config.json:
```python
async def bot_help(update: Update, context: ut.Context) -> None:
    uid = ut.uid(update)
    await ut.send(update, f"Your telegram uid is: {uid}")
```
The bot will send you a message with your uid, use that in config.json
```json
"accounts": {
        "uid here like, i.e., 123132132": {
```

**Comment by DenSwitch** [comment]
uid is exactly the same as i entered it before
do i need to set it like

```
"accounts": {
        "uid here like, i.e., 123132132": {
```

?

![image](https://user-images.githubusercontent.com/47791189/197625245-441b9824-47fe-45a9-baf6-b6e861eb4131.png)

**Comment by scmanjarrez** [comment]
Wait, you should replace the text "telegram_id" with your actual uid, e.g. 
```
"accounts": {
        "123132132": {
```
123132132 should be replaced with the uid returned from the bot

**Comment by DenSwitch** [comment]
fine, it works now. instructions unclear, need to be something like "REPLACE_THIS_WITH_YOUR_TELEGRAM_ID" for people like me :) 
thanks a lot!

**Comment by scmanjarrez** [comment]
I'll update the README with clear instructions, I'm sorry!
